### ISSUE TITLE
[FEAT] 일상 등록 기능 구현

### ISSUE THREAD

**Issue by Hwater00** [yoonhaorg/Duktown_Backend#6]
## 🔥 Feature Issue
일상 게시판 등록 기능 구현

## ✅ TODO
 - [x]  DailyController
 - [x] DailyService
 - [x] DailyRepository
 - [x] DailyDto
 - [ ] 테스트 코드 작성

**Comment by Hwater00** [comment]
1. 토큰은 로그인 시가 아니라 회원 가입 시 진행?
2. 일상 작성자인지 확인하기 위해서는 항상 request로 token을 받아야 하는건가?
3. 커스텀 에러 작성 방법?  `customErrorType`, `CustomException`

**Comment by sharpie1330** [comment]
1. 토큰은 로그인, 회원 가입 시 모두 발급됩니다!
2. 현재 덕타운에서 모든 기능이 로그인 시에만 활성화되므로 회원인지 확인하기 위해 꼭 token을 받아야 합니다.
3. 커스텀에러 작성 방법은 저도 추후 수정할 부분이라 이부분은 같이 논의해보면 좋겠네요!
