### ISSUE TITLE
[FEAT] 장터 기능 구현

### ISSUE THREAD

**Issue by ssohee98** [yoonhaorg/Duktown_Backend#7]
## 🔥 Feature Issue
장터 게시판 구현

## ✅ TODO
 - [ ] MarketDTO
 - [ ] MarketRepository
 - [ ] MarketService
 - [ ] MarketController
 - [ ] Market CRUD

**Comment by sharpie1330** [comment]
일상, 장터 기능이 동일하므로 Post로 통합, 따라서 구현 x
